# Generated by Django 4.0.2 on 2022-03-28 09:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Max 127 characters length', max_length=127, verbose_name='Title')),
                ('descrition', models.CharField(blank=True, max_length=512, null=True, verbose_name='Article description')),
                ('publication_date', models.DateField(default=datetime.datetime(2022, 3, 28, 9, 4, 16, 35836, tzinfo=utc), verbose_name='Date of publication')),
                ('slug', models.SlugField(unique_for_date='publication_date', verbose_name='Slug')),
                ('main_page', models.BooleanField(default=False, help_text='Show on main page', verbose_name='Main page')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Aticles',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Max 255 characters length', max_length=255, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Article category',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Image')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_blog.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Image for Article',
                'verbose_name_plural': 'Images for Articles',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='app_blog.category', verbose_name='Category'),
        ),
    ]
