# Generated by Django 4.0 on 2022-04-12 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publication_date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Article category', 'verbose_name_plural': 'Articles categories'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='descrition',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 12, 6, 48, 26, 607691, tzinfo=utc), verbose_name='Date of publication'),
        ),
    ]
