# Generated by Django 4.0 on 2022-04-12 06:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_article_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 12, 6, 51, 27, 999024, tzinfo=utc), verbose_name='Date of publication'),
        ),
    ]
