# Generated by Django 4.0 on 2022-04-12 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_alter_article_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of publication'),
        ),
    ]
